import os


GLOBUS_CLIENT_ID = os.getenv('GLOBUS_CLIENT_ID')
GLOBUS_CLIENT_SECRET = os.getenv('GLOBUS_CLIENT_SECRET')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')
